[project]
name = "xlpro"
version = "0.6.0"
description = "See http://xlpro.pages.dev for further information."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # xlpro_module
    "debugpy>=1.8.16",
    "filelock>=3.18.0",
    "matplotlib>=3.10.5",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "psutil>=7.0.0",
    "pywin32>=311",
    "readchar>=4.2.1",
    "rich>=14.1.0",
    # win32typelibs
]


[project.optional-dependencies]
dev = [
    # build
    "setuptools>=80.9.0",
    "build>=1.3.0",
    "pyinstaller>=6.15.0",
    
    # other
    "pip-licenses>=5.0.0",

    # xlpro_cli_shell_wrapper
    "pyinstaller-versionfile>=3.0.1",
]

# [tool.uv.editable-dependencies]
# xlpro = { path = "xlpro_module"}
# xlpro-cli = { path = "xlpro_cli"}