[project]
name = "xlpro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.2.2.post1",
    "debugpy>=1.8.14",
    "filelock>=3.18.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "olefile>=0.47",
    "oletools>=0.60.2",
    "pandas>=2.3.0",
    "psutil>=7.0.0",
    "pyinstaller>=6.14.2",
    "pyinstaller-versionfile>=3.0.1",
    "pywin32>=310",
    "readchar>=4.2.1",
    "rich>=14.0.0",
    "setuptools>=80.9.0",
    "typer>=0.16.0",
]
