[project]
name = "xlpro"
version = "0.6.0"
description = "See http://xlpro.pages.dev for further information."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # xlpro_module
    "debugpy>=1.8.4",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "psutil>=7.0.0",
    "pywin32>=309",
    "filelock>=3.18.0",
    "numpy>=2.3.1",
    "readchar>=4.2.1",
    "rich>=13.9.4",
    # "win32typelibs",
    "pip-licenses>=5.0.0",
]

[project.optional-dependencies]
dev = [
    # build
    "setuptools>=80.9.0",
    "build>=1.2.2.post1",
    "pyinstaller>=6.14.2",
    
    # other
    "pip-licenses>=5.0.0",

    # xlpro_cli_shell_wrapper
    "pyinstaller-versionfile>=3.0.1",
]

# [tool.uv.editable-dependencies]
# xlpro = { path = "xlpro_module"}
# xlpro-cli = { path = "xlpro_cli"}