
[project]
name = "xlpro_cli"
version = "0.0.7" # Placeholder will be auto-synced
description = "xlpro Command Line Interface"
readme = "N/A"
license = { text = "MIT License" }
authors = [{ name = "Daniel Evans", email = "danielevans@users.noreply.github.com" }]

requires-python = ">=3.10"
dependencies = [
    "debugpy>=1.8.16",
    "psutil>=7.0.0",
    "pywin32>=311",
    "readchar>=4.2.1",
    "rich>=14.1.0",
    # "win32typelibs",
    "tomli>=2.2.1",
]

[project.scripts]
xlpro-cli = "xlpro_cli.commands:main"
