xlpro_functions_stem = "functions"
xlpro_subroutines_stem = "subroutines"

MAX_WORKERS = 24

LOGGING_LEVEL = "DEBUG"

# XLPRO_CLI_PATH = "xlpro-cli.exe"
# VSCODE_PATH = "code.exe"
# For custom paths, ensure backslashes are not escaped. Use double backslashes '\\' or single forward slashes '/'
XLPRO_CLI_PATH = "C:/Users/Daniel Evans/projects/xlpro/.venv/Scripts/xlpro-cli.exe"
VSCODE_PATH = "C:/Users/Daniel Evans/AppData/Local/Programs/Microsoft VS Code/Code.exe"

UNDO_STACK_DEPTH = 12

MULTI_SERVER_EXPERIEMENT = false