# config.toml
# xlpro app configuration file

# Ensure backslashes are escaped correctly. 
# Use double backslashes '\\' or single forward slashes '/'

VSCODE_PATH = "code.exe"

# Set the max depth of the custom undo stack in Excel
UNDO_STACK_DEPTH = 12

XLPRO_CLI_PATH = "xlpro-cli.exe" # No need to modify
XLPRO_SERVER_PATH = "xlpro-server.exe" # No need to modify
