; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "xlpro"
#define MyAppVersion "0.0.7"
#define MyAppPublisher "Daniel Evans"
#define MyAppURL "https://xlpro.pages.dev"
#define MyAppExeName "xlpro-cli.exe"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
Uninstallable=yes
AppId={{1D3CCF30-5568-496F-B638-7893097D691B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={code:GetUserProfile}\.xlpro
DisableDirPage=yes
UsePreviousAppDir=no

SetupIconFile=favicon.ico
UninstallDisplayIcon={app}\xlpro-cli.exe
WizardImageFile=installer-splash-1.bmp
WizardSmallImageFile=inno-small.bmp

UninstallFilesDir={app}

; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=dist
OutputBaseFilename={#MyAppName}-v{#MyAppVersion}-installer
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\xlpro_installer\install\*"; DestDir: {app}; Flags: recursesubdirs ignoreversion
Source: "..\xlpro_installer\install\src\xlpro.xlam"; DestDir: {code:GetUserProfile}\AppData\Roaming\Microsoft\Excel\XLSTART; Flags: ignoreversion

[Icons]
; Name: "favicon.ico"; Filename: "{uninstallexe}"

[Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[InstallDelete]
; Type: filesandordirs; Name: {#GetEnv('USERPROFILE')}\AppData\Roaming\Microsoft\Excel\XLSTART\xlpro.xlam;

[Registry]
Root: HKCU; Subkey: "Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Check: NeedsAddPath('{app}')
    
[Dirs]
Name: "{app}"; Flags: uninsalwaysuninstall

[UninstallDelete]
Type: filesandordirs; Name: "{app}\envs"
Type: filesandordirs; Name: "{app}\uv"

[Code]
function GetUserProfile(Param: string): string;
begin
  // Expands the USERPROFILE environment variable
  Result := ExpandConstant('{%USERPROFILE}');
end;

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  { look for the path with leading and trailing semicolon }
  { Pos() returns 0 if not found }
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;


[Code]
function IsAppRunning(const FileName : string): Boolean;
var
    FSWbemLocator: Variant;
    FWMIService   : Variant;
    FWbemObjectSet: Variant;
begin
    Result := false;
    FSWbemLocator := CreateOleObject('WBEMScripting.SWBEMLocator');
    FWMIService := FSWbemLocator.ConnectServer('', 'root\CIMV2', '', '');
    FWbemObjectSet :=
      FWMIService.ExecQuery(
        Format('SELECT Name FROM Win32_Process Where Name="%s"', [FileName]));
    Result := (FWbemObjectSet.Count > 0);
    FWbemObjectSet := Unassigned;
    FWMIService := Unassigned;
    FSWbemLocator := Unassigned;
end;


function InitializeSetup(): Boolean;
var
  Answer: Integer;
  AppName: String;
begin
  AppName := 'EXCEL.exe';
  Result := True;
  while IsAppRunning(AppName) do
  begin
    Answer := MsgBox(AppName + ' must be closed during installation, please save your files and close, then press OK to continue. Press Cancel to exit. Check for process `Microsoft Excel` in Task Manager if Excel appears to be closed but this message continues.', mbError, MB_OKCANCEL);
    if Answer = IDCANCEL then
    begin
      Result := False
      Exit;
    end;
  end;
end;

function InitializeUninstall(): Boolean;
var
  Answer: Integer;
  AppName: String;
begin
  AppName := 'EXCEL.exe';
  Result := True;
  while IsAppRunning(AppName) do
  begin
    Answer := MsgBox(AppName + ' must be closed during uninstallation, please save your files and close, then press OK to continue. Press Cancel to exit. Check for process `Microsoft Excel` in Task Manager if Excel appears to be closed but this message continues.', mbError, MB_OKCANCEL);
    if Answer = IDCANCEL then
    begin
      Result := False
      Exit;
    end;
  end;
end;


[Code]
const
  WM_SETTINGCHANGE = $001A;

function SendMessage(hWnd: Integer; Msg: Integer; wParam: Integer; lParam: String): LongInt;
  external 'SendMessageW@user32.dll stdcall';

procedure NotifyEnvironmentChange;
begin
  // Broadcast to all top-level windows that environment has changed
  SendMessage(HWND_BROADCAST, WM_SETTINGCHANGE, 0, 'Environment');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    NotifyEnvironmentChange;
end;